apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{.Release.Name}}-view-only-binding
subjects:
  - kind: ServiceAccount
    name: admin-sa
    namespace: {{.Release.Name}}
roleRef:
  kind: ClusterRole
  name: view-only
  apiGroup: rbac.authorization.k8s.io
