apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Release.Name }}-deny-other-namespaces"
  namespace: {{ .Release.Name }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
        - ipBlock:
            cidr: 0.0.0.0/0
  egress:
    - to:
        - podSelector: {}
        - ipBlock:
            cidr: 0.0.0.0/0
