{{- $namespace := .Release.Name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
  namespace: {{ $namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]