{{- $namespace := .Release.Name }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: {{ $namespace }}
subjects:
  - kind: ServiceAccount
    name: admin-sa
    namespace: {{ $namespace }}
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io