apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluentd
  labels:
    app: fluentd
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  - nodes
  - events
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "logs"
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
